// <auto-generated />
using System;
using Leads.Infrastructure.MySqlDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Leads.Infrastructure.Migrations.JobsEventSourcingDb
{
    [DbContext(typeof(JobsEventSourcingDbContext))]
    partial class JobsEventSourcingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Leads.Application.Services.JobEventsSource.JobEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("date_created")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("EventData")
                        .HasColumnName("event_data")
                        .HasColumnType("JSON");

                    b.Property<Guid>("EventId")
                        .HasColumnName("event_id")
                        .HasColumnType("char(36)");

                    b.Property<string>("EventName")
                        .HasColumnName("event_name")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("EventType")
                        .HasColumnName("event_type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnName("reference_id")
                        .HasColumnType("char(36)");

                    b.HasKey("Id")
                        .HasAnnotation("MySql:ValueGeneratedOnAdd", true);

                    b.HasIndex("EventId")
                        .HasName("i_x_job_events_event_id");

                    b.HasIndex("EventName")
                        .HasName("i_x_job_events_event_name");

                    b.HasIndex("ReferenceId")
                        .HasName("i_x_job_events_reference_id");

                    b.ToTable("job_events");
                });
#pragma warning restore 612, 618
        }
    }
}
